#!/bin/bash

source $WS_CFG_PATH/ws-shared

main () {
	_ws_log verbose "Unlinking script ..."

	if [ -e "${WS_CFG_PATH}/bin/moiety" ]; then
		_ws_log verbose "Removing '${WS_CFG_PATH}/bin/moiety' ..."
		rm "${WS_CFG_PATH}/bin/moiety"
	else
		_ws_log warning "moiety was not installed. Skipping."
	fi

	return 0
}

main $*
